### ISSUE TITLE
Thank you for this, but won't run

### ISSUE THREAD

**Issue by terry9873** [zakosaba/wireguard-macos-app#1]
Hi, I am running Mac OSX 10.14.6 (I know I know, I just refuse to use any newer version, will move to Linux when I can, done with Apple!)
In mean time I wanted to try Wireguard app so someone referred me to this excellent piece of work! I downloaded the zip, extracted, but it won't run (no entry sign on icon). Weirdly, the error says "this app is designed to run on OSX 10.12 and later" ??!!

Any advice appreciated, thanks.

**Comment by vaardan** [comment]
Hello, on the WireGuard's App Store page in the compatibility section it says that it requires MacOS 12.0 or later. I guess you could try downloading it from App Store and presumably it will download the latest version supported by your machine. Or just use cli while you're still on MacOS. But I assume you'd not want to do either of those things, yet those are the only options I think.

**Comment by terry9873** [comment]
Thanks

**Comment by vaardan** [comment]
@terry9873 you might be interested in #2. Previous version 1.0.15 was provided there. It should run on your Mac OSX 10.14.6
