### ISSUE TITLE
Release 1.0.15 for older macOS version

### ISSUE THREAD

**Issue by Kaspik** [zakosaba/wireguard-macos-app#2]
Hey! Would you be able to do the same but from 1.0.15 release tag [here](https://github.com/WireGuard/wireguard-apple/releases/tag/1.0.15-26)? The problem is that for macOS below 12 there is no `dmg` available anywhere right now.

**Comment by vaardan** [comment]
Hi, I don't think so. I downloaded the last version of off Apples's official store. I wasn't able to find any other places where the app images can be downloaded. This is why I created this repo in the first place. 

Everybody in Big Tech is compulsive data hoarders, so I'm pretty sure Apple has previous versions kept somewhere. They just don't allow people to download them. I tried looking for ways to get them, because it has been requested before, but didn't find a way to do that.

**Comment by qianhd** [comment]
> Hi, I don't think so. I downloaded the last version of off Apples's official store. I wasn't able to find any other places where the app images can be downloaded. This is why I created this repo in the first place.
> 
> Everybody in Big Tech is compulsive data hoarders, so I'm pretty sure Apple has previous versions kept somewhere. They just don't allow people to download them. I tried looking for ways to get them, because it has been requested before, but didn't find a way to do that.

@vaardan   here is 1.0.15 

[Uploading WireGuard.app_1.0.15.zip…]()

**Comment by qianhd** [comment]
> Hi, I don't think so. I downloaded the last version of off Apples's official store. I wasn't able to find any other places where the app images can be downloaded. This is why I created this repo in the first place.
> 
> Everybody in Big Tech is compulsive data hoarders, so I'm pretty sure Apple has previous versions kept somewhere. They just don't allow people to download them. I tried looking for ways to get them, because it has been requested before, but didn't find a way to do that.

@vaardan  here is 1.0.15, please put it into your releases.


[WireGuard.app_1.0.15.zip](https://github.com/vaardan/wireguard-macos-app/files/14211914/WireGuard.app_1.0.15.zip)

**Comment by vaardan** [comment]
For the record:

[VirusTotal scan](https://www.virustotal.com/gui/file/df84eab7d5b991164d508c1a4c8596d428a4cf6a20cc201716adc0cf0f6bed75/details) of  v1.0.16 uploaded by me.

[VirusTotal scan](https://www.virustotal.com/gui/file/d31ea7a0441c695db234e4684901acbc8126c05b56e8e19d7ffa4a0305322066/details) of v1.0.15 uploaded by qianhd.

No detection for both files. Both files singed by Apple Inc. with key valid from `09:40 PM 04/25/2006` to `09:40 PM 02/09/2035` using algo `sha1WithRSAEncryption` with thumbprint `611E5B662C593A08FF58D14AE22452D198DF6C60`.

Relevant info from `WireGuard.app/Contents/Info.plist` of v1.0.15:
- `LSMinimumSystemVersion`: `10.14`
- `CFBundleShortVersionString`: `1.0.15`

**Comment by vaardan** [comment]
@qianhd thanks a lot for your contribution! I will add it to releases soon!

**Comment by vaardan** [comment]
@Kaspik can you try out this one and tell if it works on your MacOS 12?

**Comment by PawellGoRu** [comment]
Thank you very much

**Comment by myadzel** [comment]
> [WireGuard.app_1.0.15.zip](https://github.com/vaardan/wireguard-macos-app/files/14211914/WireGuard.app_1.0.15.zip)

Thanks!
