### ISSUE TITLE
Sharing over WiFi doesn't work

### ISSUE THREAD

**Issue by ballo** [zakosaba/wireguard-macos-app#3]
Unfortunately, there is no official way to report bugs, so I'm hoping at least one other Mac user can at least confirm this bug. 

If I share a connection to WiFi (under "Internet Sharing") it works for any service including VPNs such as L2TP/IPSec, but it does not work with WireGuard.

**Comment by vaardan** [comment]
Hi, I just re-uploaded the executables. You should address that question to the actual developers of the app here:
https://github.com/WireGuard/wireguard-apple

**Comment by ballo** [comment]
> Hi, I just re-uploaded the executables. You should address that question to the actual developers of the app here: https://github.com/WireGuard/wireguard-apple

How? I can't file an issue. I think the devs are hiding
